option('libonly', type: 'boolean', description: 'Build library only')
option('tests', type: 'feature', description: 'Build tests')
option(
    'openpower-pel-extension',
    type: 'feature',
    description: 'Create PELs',
    value: 'disabled',
)

option(
    'nvbmc-logging-extension',
    type: 'feature',
    description: 'Enable NVBMC Device Event Log Extensions for BootEntryID support',
    value: 'disabled',
)

option(
    'sel-extension',
    type: 'feature',
    description: 'Enable SEL support',
    value: 'disabled',
)

option(
    'nvidia-platform-event-extension',
    type: 'feature',
    description: 'Enable NVIDIA Platform Event extension for device error aggregation',
    value: 'disabled',
)

option(
    'max_errors_per_class',
    type: 'integer',
    value: 10,
    description: 'Maximum number of errors to store per error class in NVIDIA Platform Event extension',
)

option('yamldir', type: 'string', description: 'Path to YAML')
option(
    'callout_yaml',
    type: 'string',
    value: 'callouts/callouts-example.yaml',
    description: 'Path to Callout YAML',
)

option(
    'error_cap',
    type: 'integer',
    value: 200,
    description: 'Max number of error entries allowed for commit',
)
option(
    'error_info_cap',
    type: 'integer',
    value: 10,
    description: 'Cap on informational (and below) severity errors',
)

option(
    'phal',
    type: 'feature',
    value: 'disabled',
    description: 'Enable support for PHAL',
)

option(
    'rsyslog_server_conf',
    type: 'string',
    value: '/etc/rsyslog.d/server.conf',
    description: 'Path to rsyslog server conf file',
)

option(
    'rsyslog_fwd_actions_conf_dir_path',
    type: 'string',
    value: '/etc/rsyslog.d',
    description: 'Path to rsyslog fwd actions conf files',
)

option(
    'rw_config_file_path',
    type: 'string',
    value: '/etc/phosphor-logging/conf/rw-config.json',
    description: 'Path to read-write phosphor-logging config file',
)

option(
    'log_purge_policy_default',
    type: 'boolean',
    value: false,
    description: 'Default value of log purge policy enabled state',
)

option(
    'enable_rsyslog_fwd_actions_conf',
    type: 'boolean',
    value: false,
    description: 'Enable the creation of fwd actions conf files by phosphor-rsyslog-config',
)

option(
    'enable_log_streaming',
    type: 'boolean',
    value: false,
    description: 'Enable log socket',
)

option(
    'enable_erase_with_callback',
    type: 'boolean',
    value: false,
    description: 'Enable callback/timer based erase for clear operations',
)

option(
    'log_streamer_socket_path',
    type: 'string',
    value: '/run/rsyslog/log_streamer_console_input',
    description: 'Path to rsyslog socket',
)

option(
    'lg2_commit_strategy',
    type: 'combo',
    choices: ['dbus', 'journal', 'both'],
    value: 'both',
)

option(
    'event-filter',
    type: 'string',
    description: 'Path to the event filter JSON file.',
)

option(
    'rsyslog_ethernet_interface',
    type: 'string',
    value: 'eth0',
    description: 'ethernet intercae acive for rsyslog',
)

option(
    'use-bmc-pos-in-id',
    type: 'boolean',
    value: true,
    description: 'If the BMC position should be encoded into the event log ID',
)

option(
    'redundant-bmc',
    type: 'boolean',
    value: false,
    description: 'Enable support for redundant BMC systems',
)
