if get_option('openpower-pel-extension').allowed()
    subdir('openpower-pels')
endif

if not get_option('nvbmc-logging-extension').disabled()
    subdir('nvbmc-logging')
endif

if not get_option('sel-extension').disabled()
    subdir('sel')
endif

if not get_option('nvidia-platform-event-extension').disabled()
    subdir('nvidia-platform-event')
endif

#subdir('nvbmc-logging')
